### ISSUE TITLE
Can't edit document 

### ISSUE THREAD

**Issue by thomas-schmidt-silver** [learnweb/moodle-assignsubmission_collabora#14]
Hello Andreas,
there is no possibility to edit the Collaborative assignment. Simply there is no Cursor showing. The activity Collaborative document works fine.
(Moodle Version 3.10.7, assignsubmission_collabora v3.11-r1)
I tried Specified text as well as Wordprocessor Document. It stays the same no Cursor.
![Screenshot 2021-11-09 130345](https://user-images.githubusercontent.com/55231072/140921057-90a839be-294d-4e85-af18-e5f7f5f01576.png)

Also i have no "Pen" Symbol.
Regards

**Comment by grabs** [comment]
Hi Thomas,
thanks for the infos!
I still can't reproduce this :(.
What version of Collabora server do you use?

**Comment by grabs** [comment]
Hi, I just did a test with Moodle Version 3.10.7+, assignsubmission_collabora v3.11-r1.
The student could edit the document without any problem.

**Comment by grabs** [comment]
Can you check your iframe url the collabora is embedded with?
Look for the WOPISrc parameter which has a callback url in it.
In the callback url is a files parameter like
`...callback.php%2Fwopi%2Ffiles%2F7e836a9285304e38fb7e419ab4856c45a5629844_600...`
This parameter has two parts:
1) the hash from the moodle file api
2) the permissions separated by an underscore in this example: _600
What is this showing in your case?

**Comment by thomas-schmidt-silver** [comment]
Hi Andreas,
sorry. It took me a while to find, what you're looking for. 
callback.php%2Fwopi%2Ffiles%2Fa91c02152fc9b917539f389691461309d8ceb803_444&amp;access_token=e369853df766fa44e1ed0ff613f563bd_34&amp;lang=de

**Comment by grabs** [comment]
Hi,
as you can see the permission is set to "444". This means your user, you are testing with, has only readonly access to this collabora submission.
One reason for this could be that your user hast two roles in the course, student + editingteacher.
Please check the user is only a student with no grading rights.
I hope that helps a little.
Best regards
Andreas

**Comment by thomas-schmidt-silver** [comment]
Hi Andreas,
thanks a lot. That solved the problem.
Best Regards
Thomas

**Comment by grabs** [comment]
Your welcome :).
