### ISSUE TITLE
If submission via Collabora is selected, students will no longer be able to submit via the app

### ISSUE THREAD

**Issue by scroom** [learnweb/moodle-assignsubmission_collabora#15]
As described above. Unfortunately, neither Collabora loads in the app (Android and IOS), nor is another submission form still possible then. Unfortunately, neither Collabora loads in the app, nor is another submission form still possible then.
Should I file this bug against the Moodle App as well?

**Comment by scroom** [comment]
Hi,

What have I done?
- I have created an exercise in a course. I have enabled Collabora and file submission as possible submission formats.

What am I expecting?
- I expected that students would at least be able to continue to submit files via the Moodle app. It would be better if they could operate both types of submission via the Moodle app.

What happens?
- Unfortunately, file submission is also no longer possible via the Moodle app, so students can no longer use the app to complete their assignments. I am attaching a screenshot of a student. She then uploaded the files that can be seen in the screenshot via the browser.

What version of Collabora do you use and also is it a dedicated server or a docker container?
- I've been using collabora 6.4 as this bug occurred (just upgraded to 21.11 afterwards - see other bug regports) on a dedicated server

What version of Moodle and also what version of Collabora-Plugin do you use?
- Moodle 3.11.4 and Plugin-version v3.11-r1 (2021102600)

Best regards
Alexander

**Comment by grabs** [comment]
Hi,
I am not sure that the Collabora submission works in the app at all.
If you could use this submission in earlier versions of collabora in the moodle app it should work also with newer versions.
After changing the collabora version you have to clear the moodle caches!
Best regards
Andreas

**Comment by scroom** [comment]
Hello,
Thank you for pointing out the need to clear the Moodle caches after updating Collabora!

We haven't integrated Collabora into Moodle for that long. These are the first courses where we are testing the Collabora submission option.

It wouldn't be nice but not particularly problematic if Collabora didn't work in the app. However, it is problematic that students can no longer submit via the app at all if submission via Collabora is also allowed.
This is currently the case.

Best regards

Alexander

**Comment by grabs** [comment]
Hi Alexander,
apparently you can't allow collabora submissions if you want students to use the app to upload their files :(.
Best regards
Andreas
